"""add subdomain & referral_code to vendors model

Revision ID: b19a7ebd5cc2
Revises: fe385c568170
Create Date: 2026-05-08 07:42:16.592399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b19a7ebd5cc2'
down_revision: Union[str, None] = 'fe385c568170'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendors', sa.Column('subdomain', sa.String(length=50), nullable=False))
    op.add_column('vendors', sa.Column('referral_code', sa.String(length=30), nullable=True))
    op.alter_column('vendors', 'business_phone_number',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.create_index(op.f('ix_vendors_business_phone_number'), 'vendors', ['business_phone_number'], unique=True)
    op.create_index(op.f('ix_vendors_subdomain'), 'vendors', ['subdomain'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vendors_subdomain'), table_name='vendors')
    op.drop_index(op.f('ix_vendors_business_phone_number'), table_name='vendors')
    op.alter_column('vendors', 'business_phone_number',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.drop_column('vendors', 'referral_code')
    op.drop_column('vendors', 'subdomain')
    # ### end Alembic commands ###