"""update phone to phone_number

Revision ID: fe385c568170
Revises: 001_initial
Create Date: 2026-05-07 22:27:24.302852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe385c568170'
down_revision: Union[str, None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(length=30), nullable=True))
    op.drop_constraint(op.f('uq_users_email'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_column('users', 'phone')
    op.add_column('vendors', sa.Column('business_phone_number', sa.String(length=30), nullable=True))
    op.drop_constraint(op.f('uq_vendors_business_email'), 'vendors', type_='unique')
    op.drop_index(op.f('ix_vendors_business_email'), table_name='vendors')
    op.create_index(op.f('ix_vendors_business_email'), 'vendors', ['business_email'], unique=True)
    op.drop_column('vendors', 'business_phone')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendors', sa.Column('business_phone', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_vendors_business_email'), table_name='vendors')
    op.create_index(op.f('ix_vendors_business_email'), 'vendors', ['business_email'], unique=False)
    op.create_unique_constraint(op.f('uq_vendors_business_email'), 'vendors', ['business_email'], postgresql_nulls_not_distinct=False)
    op.drop_column('vendors', 'business_phone_number')
    op.add_column('users', sa.Column('phone', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_unique_constraint(op.f('uq_users_email'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###